const { test, expect } = require('@playwright/test');
const CategoryPage = require('../../page-objects/CategoryPage');
const ProductsPage = require('../../page-objects/ProductsPage');
const { query } = require('../../utils/db-client');

test.describe.serial('4.3 Category & Collection Management UI', () => {
    let categoryPage;
    let originalCat;
    let productsPage;
    let categoryId;
    let subCategoryId;
    let expectedSlugValue;
    let categoryResult;
    let productIds;
    let listingsBefore;
    const runId = Date.now();
    const updatedCategoryTitle = `Updated Test Category ${runId}`;
    let controlProductIds;
    const category = {
        name: `Test Category ${runId}`,
        description: 'This is a test category',


    };
    const childCategory = {
        name: `Child Test Category ${runId}`,
        description: 'This is a child test category',


    }

    const product = {
        productType: "Default Type",
        name: 'Monospace Tee',
        description: `A product assigne to ${category.name}`,
        rating: 3,
        shippingWeight: 40,
        channels: [
            { name: 'Channel-USD', sellingPrice: "30", costPrice: "28" },
            { name: 'Channel-PLN', sellingPrice: "45", costPrice: "40" },
        ],
        sku: 'test-category-product-01',
        trackInventory: true,
        category: `${updatedCategoryTitle}`,
        collections: ['Summer Picks'],
    };

    test.beforeEach(async ({ page }) => {
        categoryPage = new CategoryPage(page);
        productsPage = new ProductsPage(page);
    });

    test.afterAll(async () => {
        if (originalCat) await query('UPDATE product_product SET category_id = $1 WHERE id = $2', [originalCat.category_id, originalCat.id]);
        if (!categoryId) return;
        try {
            const tree = await query(
                `WITH RECURSIVE t AS (
               SELECT id, 0 AS depth FROM product_category WHERE id = $1
               UNION ALL
               SELECT c.id, t.depth + 1 FROM product_category c JOIN t ON c.parent_id = t.id
             ) SELECT id FROM t ORDER BY depth DESC`, [categoryId]);
            const ids = tree.map(r => r.id);
            if (ids.length) {
                await query('UPDATE product_product SET category_id = NULL WHERE category_id = ANY($1)', [ids]);
                for (const id of ids) await query('DELETE FROM product_category WHERE id = $1', [id]);
            }
        } catch (err) {
            console.log(`category cleanup: failed: ${err.message}`);
        }
    });

    test('A. Category — Create (P0)', async ({ page }) => {
        await test.step('CAT-UI-001 should create a top-level category with required fields via the UI', async () => {
            await page.goto('/dashboard/categories');
            await categoryPage.createCategory(category);
        })

        await test.step('CAT-UI-002 should auto-generate the slug from the category name', async () => {
            const autogeneratedSlug = await categoryPage.fetchGeneratedSlug();
            expectedSlugValue = category.name.trim().toLowerCase().replace(/\s+/g, '-')
            expect(autogeneratedSlug).toBe(expectedSlugValue);
        })

        await test.step('CAT-UI-003 should derive description_plaintext correctly from rich-text input', async () => {
            categoryResult = await query('SELECT * FROM product_category WHERE name = $1 LIMIT 1', [category.name]);
            categoryId = categoryResult[0].id;
            expect(categoryResult[0].description.blocks[0].data.text.trim()).toBe(category.description.trim());
        })

        await test.step('CAT-UI-004 should create a nested (child) category under an existing parent', async () => {
            await page.goto('/dashboard/categories');
            await categoryPage.navigateToParentCategory(category.name);
            await categoryPage.createChildCategory(childCategory);
            const childCategories = await categoryPage.fetchCategories();
            expect(childCategories).toContain(childCategory.name);
            // console.log(childCategories);
            const res = await query('SELECT * FROM product_category WHERE name = $1 LIMIT 1', [childCategory.name]);
            subCategoryId = res[0].id;
            expect(res[0].parent_id).toBe(categoryId);

        })
    })

    test('B. Category — Validation (P1)', async ({ page }) => {
        let categoryUpdateCalled = false;
        await test.step('CAT-UI-005 should show a validation error when the category name is empty', async () => {

            await page.route('**/graphql/', async (route) => {
                const request = route.request();
                const postData = request.postDataJSON(); // parses the JSON body for you
                console.log(postData?.query);
                if (postData?.query?.includes('productUpdate')) {
                    categoryUpdateCalled = true;
                }

                await route.continue(); // always let the request through — this is an observer, not a blocker

            });
            await page.goto('/dashboard/categories');
            await categoryPage.navigateToParentCategory(category.name);
            const isSubmitEnabled = await categoryPage.assertValidationError(category.name);
            expect(isSubmitEnabled).toBe(false);
        })

        await test.step('CAT-UI-006 should not fire a categoryCreate request when validation fails', async () => {
            expect(categoryUpdateCalled).toBe(false);
            await page.unroute('**/graphql/');
        })

        await test.step('CAT-UI-007 should show a specific error when saving a duplicate slug', async () => {
            const isErrorVisible = await categoryPage.slugDuplicationValidation('accessories');
            expect(isErrorVisible).toBe(true);
        })
    })

    test('C. Category — Update (P0)', async ({ page }) => {
        await test.step('CAT-UI-008 should update the category name and reflect it immediately in the UI', async () => {
            await page.goto('/dashboard/categories');
            await categoryPage.navigateToParentCategory(category.name);
            await categoryPage.updateCategoryTitle(updatedCategoryTitle);
        })

        await test.step('CAT-UI-009 should NOT change the slug when only the name is updated', async () => {
            const slug = await categoryPage.fetchCurrentSlug();
            expect(slug).toBe(expectedSlugValue);
        })

        await test.step('CAT-UI-010 should advance updated_at while created_at stays fixed', async () => {
            const updatedRes = await query('SELECT * FROM product_category WHERE id = $1 LIMIT 1', [categoryId])
            console.log(`Initial updated at is ${categoryResult[0].updated_at} while now it is ${updatedRes[0].updated_at}`);
            expect(new Date(updatedRes[0].updated_at).getTime()).toBeGreaterThan(new Date(categoryResult[0].updated_at).getTime());
        })
    })

    test('D. Assign Products to test category - Product Assignment', async ({ page }) => {
        originalCat = (await query('SELECT id, category_id FROM product_product WHERE name = $1', [product.name]))[0];
        await page.goto('/dashboard/categories');
        await categoryPage.navigateToParentCategory(category.name);
        await categoryPage.navigateToAssignedProducts();
        await categoryPage.assignProduct(product);
        await page.goto('/dashboard/categories');
        await categoryPage.navigateToParentCategory(category.name);
        await categoryPage.navigateToAssignedProducts();
        await expect.poll(
            async () => (await query('SELECT id FROM product_product WHERE category_id = $1', [categoryId])).length,
            { message: 'product not assigned to test category', timeout: 10_000 }
        ).toBeGreaterThan(0);

    })

    test('E. Category — Delete (P0)', async ({ page }) => {
        await test.step('CAT-UI-011 should require confirmation before deleting a category', async () => {

            // Fetching products under category sweatshirts with ID 29 to see if the deletion of this custom category has any
            // effect on its products

            controlProductIds = (await query(
                'SELECT id FROM product_product WHERE category_id = $1',
                [29] // sweatshirts category_id = 29
            )).map(p => p.id);
            console.log('Product IDs are: ', controlProductIds);

            // productIds = await query(
            //     'SELECT id, name FROM product_product WHERE category_id = $1',
            //     [categoryId]
            // );
            // expect(productIds.length).toBeGreaterThan(0);

            await expect.poll(async () => {
                productIds = await query('SELECT id, name FROM product_product WHERE category_id = $1', [categoryId]);
                return productIds.length;
            }, { message: `no products assigned to category ${categoryId}`, timeout: 10_000 }).toBeGreaterThan(0);

            listingsBefore = await query(
                'SELECT product_id, is_published, visible_in_listings FROM product_productchannellisting WHERE product_id = ANY($1)',
                [productIds.map(p => p.id)]
            );
            await page.goto('/dashboard/categories');
            await categoryPage.navigateToParentCategory(category.name);
            const isWarned = await categoryPage.deletionWarning();
            expect(isWarned).toBe(true);
        })

        await test.step('CAT-UI-012 should remove the category from the list after deletion', async () => {
            const updatedCategoryList = await categoryPage.confirmDeletion();
            expect(updatedCategoryList).not.toContain(category.name);

        })

        await test.step('CAT-UI-013 should actually delete the row, not soft-delete', async () => {
            const res = await query('SELECT * FROM product_category where id = $1', [categoryId]);
            expect(res).toEqual([]);
        })

        await test.step('CAT-UI-014 should determine what happens to products still assigned to a deleted category', async () => {
            const productsAfter = await query(
                'SELECT id, name, category_id FROM product_product WHERE id = ANY($1)',
                [productIds.map(p => p.id)]
            );
            expect(productsAfter.length).toBe(productIds.length);
            for (const product of productsAfter) {
                expect(product.category_id).toBeNull();
            }

            const listingsAfter = await query(
                'SELECT product_id, is_published, visible_in_listings FROM product_productchannellisting WHERE product_id = ANY($1)',
                [productIds.map(p => p.id)]
            );
            console.log('Listing after category deletion is: ', listingsAfter);

            const controlProductsAfter = await query(
                'SELECT id, category_id FROM product_product WHERE id = ANY($1)',
                [controlProductIds] // products never in the deleted category
            );
            for (const p of controlProductsAfter) {
                expect(p.category_id).not.toBeNull();
            }

            for (const before of listingsBefore) {
                const after = listingsAfter.find(l => l.product_id === before.product_id);
                expect(after.is_published).toBe(false);
                expect(after.visible_in_listings).toBe(before.visible_in_listings);
            }
        });
    })

});